name: Gettext (Babel) & Crowdin upload

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build-and-gettext:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -U -r requirements.txt

      - name: Run gettext extract
        run: |
          python ./bot.py update_babel
      
      - name: Git Auto Commit gettext
        uses: stefanzweifel/git-auto-commit-action@v4.14.1
        with:
          file_pattern: '*.pot'
          commit_message: Update gettext translations


  crowdin:
    needs: build-and-gettext
    runs-on: ubuntu-latest
    
    steps:
      - name: crowdin action
        uses: crowdin/github-action@1.4.12
        with:
          upload_translations: true
          download_translations: false
          config: "crowdin.yml"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_API_KEY }}
